[hololens]
package = "holo/lens-helm"
chart_path = "charts/cert-manager"
value_files = [
    "manifests/helm-values.yaml",
    "values.yaml"
]
kube_version = "1.18.0"

[hololens.input]
root = "infra/cert-manager"

[hololens.output]
merge = "replace"
