[hololens]
package = "holo/lens-helm3/1.2"

[hololens.helm]
namespace = "cert-manager"
release_name = "cert-manager"

chart_path = "charts/cert-manager"
value_files = [
    "manifests/helm-values.yaml",
    "values.yaml"
]

[hololens.input]
root = "cert-manager"
files = "**"

[hololens.output]
merge = "replace"
