[hololens]
package = "holo/lens-helm3/1.2"

[hololens.helm]
namespace = "cert-manager"
release_name = "cert-manager"

chart_path = "helm-chart"
value_files = [
    "helm-values.yaml",
    "default-values.yaml",
    "release-values.yaml"
]

[hololens.input]
root = "cert-manager"
files = "**"

[hololens.output]
merge = "replace"
