apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/version: v0.17.4
    helm.sh/chart: sealed-secrets-2.1.5
  name: sealed-secrets
  namespace: sealed-secrets
