apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: 'cert-manager:leaderelection'
  namespace: kube-system
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
    helm.sh/chart: cert-manager-v0.1.0
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    resourceNames:
      - cert-manager-controller
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - create
