apiVersion: v1
data:
  admin-password: YkhwR0k0OE5WdWJhOEJXWUlwbHo5aUdQUEdqclI1Z0JCNTZWc2FVSw==
  admin-user: YWRtaW4=
  ldap-toml: ''
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.3.5
    helm.sh/chart: grafana-6.2.1
  name: grafana
  namespace: grafana
type: Opaque
