# Strip bazel templating in a bootleg fashion

[hololens]
package = "holo/lens-shell/1.0"

[hololens.shell]
script = '''
sed -i'' -E 's/^(appVersion|version):.*/\1: v1.10.1/g' Chart.template.yaml
mv -v Chart.template.yaml Chart.yaml
'''

[hololens.input]
files = "**"

[hololens.output]
merge = "replace"
