apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app: loki
    chart: loki-2.9.2
    heritage: Helm
    release: loki
  name: loki
  namespace: loki
