site_name: Cluster Documentation
edit_uri: edit/main/docs

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: "light blue"
    accent: "amber"

plugins:
  - search
  - awesome-pages
  - macros

extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: '!!python/name:pymdownx.superfences.fence_div_format'
  - pymdownx.smartsymbols
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  - smarty

extra:
  cluster:
    cluster_issuer: letsencrypt-prod
