name: Update tag projections

on:
  push:
    tags: [ 'v*' ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  HAB_LICENSE: accept-no-persist


jobs:
  update-tag-projections:
    runs-on: ubuntu-latest
    steps:

    - name: 'Update holobranch: k8s/blueprint/common'
      uses: JarvusInnovations/hologit@actions/projector/v1
      with:
        holobranch: k8s-blueprint
        commit-to: k8s/blueprint/common

    - name: 'Update holobranch: k8s/manifests/common'
      uses: JarvusInnovations/hologit@actions/projector/v1
      with:
        holobranch: k8s-manifests
        commit-to: k8s/manifests/common
